In [17]:
from tensorflow.keras.preprocessing.text import one_hot
import numpy as np

In [9]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [24]:
voc_size=10000

In [25]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9627, 3320, 4575, 3152],
 [9627, 3320, 4575, 2811],
 [9627, 9216, 4575, 6542],
 [7339, 1095, 9203, 4969, 1299],
 [7339, 1095, 9203, 4969, 8620],
 [1880, 9627, 7762, 4575, 9500],
 [7962, 1872, 6624, 4969]]

In [26]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [27]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9627 3320 4575 3152]
 [   0    0    0    0 9627 3320 4575 2811]
 [   0    0    0    0 9627 9216 4575 6542]
 [   0    0    0 7339 1095 9203 4969 1299]
 [   0    0    0 7339 1095 9203 4969 8620]
 [   0    0    0 1880 9627 7762 4575 9500]
 [   0    0    0    0 7962 1872 6624 4969]]


In [28]:
dim=10

In [29]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [30]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [36]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


array([[[-0.01927989, -0.02462407,  0.03137132,  0.00305868,
          0.03360914,  0.02383463,  0.04718497, -0.03329384,
          0.02088619,  0.02878257],
        [-0.01927989, -0.02462407,  0.03137132,  0.00305868,
          0.03360914,  0.02383463,  0.04718497, -0.03329384,
          0.02088619,  0.02878257],
        [-0.01927989, -0.02462407,  0.03137132,  0.00305868,
          0.03360914,  0.02383463,  0.04718497, -0.03329384,
          0.02088619,  0.02878257],
        [-0.01927989, -0.02462407,  0.03137132,  0.00305868,
          0.03360914,  0.02383463,  0.04718497, -0.03329384,
          0.02088619,  0.02878257],
        [ 0.04655296, -0.01311995, -0.04331706, -0.04175627,
         -0.03157568, -0.04172266,  0.0410717 , -0.02224643,
         -0.00321144, -0.03709261],
        [-0.02049454,  0.04727015, -0.04049194, -0.03731873,
         -0.02708315, -0.01160594, -0.0326108 , -0.0225655 ,
         -0.02839032, -0.03415004],
        [ 0.01823146, -0.01229148, -0.01071278,  0.0

In [37]:
embedded_docs[0]

array([   0,    0,    0,    0, 9627, 3320, 4575, 3152])

In [46]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


array([[[-0.01927989, -0.02462407,  0.03137132,  0.00305868,
          0.03360914,  0.02383463,  0.04718497, -0.03329384,
          0.02088619,  0.02878257],
        [-0.01927989, -0.02462407,  0.03137132,  0.00305868,
          0.03360914,  0.02383463,  0.04718497, -0.03329384,
          0.02088619,  0.02878257],
        [-0.01927989, -0.02462407,  0.03137132,  0.00305868,
          0.03360914,  0.02383463,  0.04718497, -0.03329384,
          0.02088619,  0.02878257],
        [-0.01927989, -0.02462407,  0.03137132,  0.00305868,
          0.03360914,  0.02383463,  0.04718497, -0.03329384,
          0.02088619,  0.02878257],
        [ 0.04655296, -0.01311995, -0.04331706, -0.04175627,
         -0.03157568, -0.04172266,  0.0410717 , -0.02224643,
         -0.00321144, -0.03709261],
        [-0.02049454,  0.04727015, -0.04049194, -0.03731873,
         -0.02708315, -0.01160594, -0.0326108 , -0.0225655 ,
         -0.02839032, -0.03415004],
        [ 0.01823146, -0.01229148, -0.01071278,  0.0